name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
  
    - name: dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov ruff

    - name: ruff
      run: |
        ruff check

    - name: pytest
      run: |
        pytest --cov-report term-missing --cov=.
